[package]
name = "aoc20"
version = "0.1.0"
authors = ["Ben Morgan <cassava@iexu.de>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
lazy_static = "1.2.0"
regex = "1.1.0"
chrono = "0.4.6"
thiserror = "1.0.22"
